import Head from 'next/head';
import {
    Box,
    Flex,
    HStack,
    Container,
    Icon,
    VisuallyHidden,
    Square,
    Link,
    Text
} from '@chakra-ui/react';
import { SiYoutube, SiDiscord, SiGithub } from 'react-icons/si';

import Logo from './logo';
import NavButtonLink from './navButtonLink';

type Props = {
    title?: string;
    children: React.ReactNode;
};

const DEFAULT_TITLE = 'DG Roundup';
const navbarHeight = 12;

const Layout = ({ title, children }: Props) => (
    <>
        <Head>
            <title>{title ?? DEFAULT_TITLE}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
            <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
            <link rel="manifest" href="/site.webmanifest" />
            <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
            <meta name="theme-color" content="#ffffff" />
        </Head>
        <Box bg="gray.100" minHeight="100vh" pt={navbarHeight + 2} position="relative">
            <Box
                as="header"
                position="fixed"
                top={0}
                left={0}
                w="100%"
                h={navbarHeight}
                bg="white"
                borderBottomWidth="1px"
                borderBottomColor="gray.300"
            >
                <Flex align="center" justify="space-between" px={8} h="100%">
                    <HStack spacing={2} fontSize="md">
                        <Logo />
                        <NavButtonLink href="/recent" label="Recent" />
                        <NavButtonLink href="/archives" label="Archives" />
                    </HStack>
                </Flex>
            </Box>
            <Container maxW="container.sm" pb={16}>
                <Box as="main">
                    <Box>{children}</Box>
                </Box>
            </Container>
            <Box as="footer" position="absolute" bottom={0} left={0} w="100%" px={8}>
                <Flex
                    align="center"
                    justify="space-between"
                    py={4}
                    borderTop="1px"
                    borderTopColor="gray.300"
                    color="gray.500"
                >
                    <Box>
                        <Text fontSize="sm">&copy; 2022 DG Roundup</Text>
                    </Box>
                    <HStack spacing={4}>
                        <Square size={6}>
                            <Link href="https://www.youtube.com/c/TheDailyGwei" w="100%" h="100%">
                                <VisuallyHidden>YouTube</VisuallyHidden>
                                <Icon as={SiYoutube} w="100%" h="100%" />
                            </Link>
                        </Square>
                        <Square size={6}>
                            <Link href="https://discord.com/invite/4pfUJsENcg" w="100%" h="100%">
                                <VisuallyHidden>Discord</VisuallyHidden>
                                <Icon as={SiDiscord} w="100%" h="100%" />
                            </Link>
                        </Square>
                        <Square size={6}>
                            <Link
                                href="https://github.com/BrandonNoad/daily-gwei-links"
                                w="100%"
                                h="100%"
                            >
                                <VisuallyHidden>GitHub</VisuallyHidden>
                                <Icon as={SiGithub} w="100%" h="100%" />
                            </Link>
                        </Square>
                    </HStack>
                </Flex>
            </Box>
        </Box>
    </>
);

export default Layout;
